### ISSUE TITLE
setup.py needed

### ISSUE THREAD

**Issue by rassie** [ross/memcache-debug-panel#1]
...otherwise it's not possible to install memcache-debug-panel in automated way.

**Comment by ross** [comment]
just (quickly) added one that should hopefully do the trick. let me know if it doesn't work.

best,
-rm

**Comment by rassie** [comment]
Thanks for the quick reply. The `setup.py` works in the sense that it installs and even includes templates. However, I still have two issues with it:
1. My `site-packages\memcache_toolbar-0.5.1-py2.6.egg-info\installed-files.txt` only contains the top-level `__init__.py`, but not any other modules or templates. Thus, templates can't be found.
2. The name `memcache_toolbar` could be problematic -- `pip` thinks it's complete name, i.e. `pip freeze` gives me `memcache-toolbar==0.5.1`. I suppose you'd want to upload this someday to PyPI under `django-memcache-toolbar` or even `django-debug-toolbar-memcache-panel` or something else with `django` in it somewhere, so I'd be nice if `pip` got the right name right away for upgrades.

**Comment by ross** [comment]
as far as the name goes i was roughly working off of the django debug toolbar itself which is debug_toolbar (at least the module it ends up installing.) 

haven't really messed with setup.py's much and don't really have the bandwidth to get it to it atm, sorry. happy to accept patches/pull requests if you want to suggest something.

best,
-rm
