### ISSUE TITLE
how to install via pip?

### ISSUE THREAD

**Issue by wingyiu** [ross/memcache-debug-panel#4]
RT

**Comment by LucasMagnum** [comment]
Try it:
pip install -e git+git://github.com/ross/memcache-debug-panel#egg=memcache_toolbar

**Comment by ross** [comment]
sorry, yeah, this hasn't been packaged and submitted to pypi. the above git trick will work well.

i'll look in to getting it in to pypi, but it make take a while before i get to it.

**Comment by Naddiseo** [comment]
_Bump_

**Comment by ross** [comment]
sorry they've changed enough with django-debug-panel that i'd be surprised if it still works. that said i would suggest the pip git install.

**Comment by ross** [comment]
https://pypi.python.org/pypi/memcache_toolbar/

**Comment by Naddiseo** [comment]
Great, thanks!
